# =====================================================
# GITHUB WORKFLOW: OVERDUE HEALTH TASK REMINDERS
# Purpose: Call unified overdue notification system every 30 minutes
# Triggers: Scheduled cron job
# =====================================================

name: Send Overdue Health Task Reminders

# Run every 30 minutes during active hours (6 AM - 11 PM Malaysia time)
# GitHub Actions uses UTC, so Malaysia time (UTC+8) 6AM = UTC 10PM (22:00)
on:
  schedule:
    # Every 30 minutes from 10 PM UTC (6 AM Malaysia) to 3 PM UTC (11 PM Malaysia)
    - cron: '*/30 22-23,0-15 * * *'  # 6 AM - 11 PM Malaysia time
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode - run immediately'
        required: false
        default: 'false'
        type: boolean

jobs:
  send-overdue-reminders:
    name: Process Overdue Health Tasks
    runs-on: ubuntu-latest
    
    # Only run if it's within active hours or manual trigger
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      
      - name: Check Malaysia time
        run: |
          echo "Current UTC time: $(date -u)"
          echo "Malaysia time: $(TZ='Asia/Kuala_Lumpur' date)"
          echo "Workflow triggered by: ${{ github.event_name }}"
      
      - name: Call overdue reminder function
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          echo "🕐 Calling unified overdue notification system..."
          
          # Call the main SQL function that handles both personal and family notifications
          RESULT=$(psql "$SUPABASE_DB_URL" -t -A -c "SELECT send_one_hour_followup_reminders();")
          
          echo "📊 Processed users with overdue tasks: $RESULT"
          
          # Optional: Get detailed statistics
          echo "📋 Getting reminder statistics..."
          psql "$SUPABASE_DB_URL" -c "
            SELECT 
              'Today followups sent' as metric,
              COUNT(*) as count 
            FROM health_task_followup_tracking 
            WHERE followup_date = CURRENT_DATE
            
            UNION ALL
            
            SELECT 
              'Today family notifications sent' as metric,
              COUNT(*) as count 
            FROM task_overdue_notifications 
            WHERE DATE(sent_at AT TIME ZONE 'Asia/Kuala_Lumpur') = CURRENT_DATE
          "
      
      - name: Handle errors
        if: failure()
        run: |
          echo "❌ Overdue reminder job failed!"
          echo "Check your SUPABASE_DB_URL secret and database connection."
          
      - name: Success notification
        if: success()
        run: |
          echo "✅ Overdue reminder job completed successfully!"
          echo "🎯 Anti-spam system active: max 1 notification per user per day"
