name: Scheduled Personalized Reminders

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  trigger-personalized-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase personalized-reminders (schedule_check)
        run: |
          curl -X POST "https://wtuwjqvgkpbvfcplkhvo.functions.supabase.co/personalized-reminders" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -d '{"action":"schedule_check"}'
