# =====================================================
# GITHUB WORKFLOW: OVERDUE REMINDERS VIA EDGE FUNCTION
# Purpose: Call existing personalized-reminders edge function
# Uses the schedule_check action that calls unified overdue system
# =====================================================

name: Send Overdue Health Task Reminders

on:
  schedule:
    # Every 30 minutes from 10 PM UTC (6 AM Malaysia) to 3 PM UTC (11 PM Malaysia)
    - cron: '*/30 22-23,0-15 * * *'  # 6 AM - 11 PM Malaysia time
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode - run immediately'
        required: false
        default: 'false'
        type: boolean

jobs:
  send-overdue-reminders:
    name: Process Overdue Health Tasks
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Malaysia time
        run: |
          echo "Current UTC time: $(date -u)"
          echo "Malaysia time: $(TZ='Asia/Kuala_Lumpur' date)"
          echo "Workflow triggered by: ${{ github.event_name }}"
      
      - name: Call unified overdue reminder system
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          echo "🕐 Calling unified overdue notification system via edge function..."
          
          # Call the personalized-reminders edge function with schedule_check action
          # This calls send_one_hour_followup_reminders() which handles both personal + family notifications
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            "https://wtuwjqvgkpbvfcplkhvo.functions.supabase.co/personalized-reminders" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -d '{"action":"schedule_check"}')
          
          # Extract HTTP status code and response body
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          
          echo "📊 HTTP Status: $HTTP_CODE"
          echo "📄 Response: $RESPONSE_BODY"
          
          # Check if request was successful
          if [ "$HTTP_CODE" -eq 200 ]; then
            echo "✅ Overdue reminder system executed successfully!"
            
            # Try to extract processed count from response
            PROCESSED=$(echo "$RESPONSE_BODY" | grep -o '"processed_count":[0-9]*' | grep -o '[0-9]*' | head -1)
            if [ -n "$PROCESSED" ]; then
              echo "👥 Users processed: $PROCESSED"
            fi
            
            # Extract other statistics if available
            ERROR_COUNT=$(echo "$RESPONSE_BODY" | grep -o '"error_count":[0-9]*' | grep -o '[0-9]*' | head -1)
            SKIPPED_COUNT=$(echo "$RESPONSE_BODY" | grep -o '"skipped_count":[0-9]*' | grep -o '[0-9]*' | head -1)
            
            if [ -n "$ERROR_COUNT" ] && [ -n "$SKIPPED_COUNT" ]; then
              echo "📈 Statistics: Processed=$PROCESSED, Errors=$ERROR_COUNT, Skipped=$SKIPPED_COUNT"
            fi
          else
            echo "❌ Request failed with HTTP $HTTP_CODE"
            echo "Error details: $RESPONSE_BODY"
            exit 1
          fi
      
      - name: Handle errors
        if: failure()
        run: |
          echo "❌ Overdue reminder job failed!"
          echo "Check your SUPABASE_SERVICE_ROLE_KEY secret and edge function status."
          echo "Verify the edge function URL is correct for your project."
          
      - name: Success notification
        if: success()
        run: |
          echo "🎉 Overdue reminder job completed successfully!"
          echo "✅ Personal reminders sent to users with overdue tasks"
          echo "✅ Family notifications sent in each member's preferred language"
          echo "🎯 Anti-spam system active: max 1 notification per user per day"
          echo "🔄 Next run in 30 minutes"
